export const countryMetaData = [
    { name: 'Albania', phoneCode: '+355', tax: '20', currencyCode: 'ALL', currencySymbol: 'Lek' },
    { name: 'Algeria', phoneCode: '+213', tax: '19', currencyCode: 'DZD', currencySymbol: 'د.ج' },
    { name: 'Andorra', phoneCode: '+376', tax: '4.5', currencyCode: 'EUR', currencySymbol: '€' },
    { name: 'Angola', phoneCode: '+244', tax: '14', currencyCode: 'AOA', currencySymbol: 'Kz' },
    { name: 'Antigua And Barbuda', phoneCode: '+1-268', tax: '15', currencyCode: 'XCD', currencySymbol: '$' },
    { name: 'Argentina', phoneCode: '+54', tax: '21', currencyCode: 'ARS', currencySymbol: '$' },
    { name: 'Armenia', phoneCode: '+374', tax: '20', currencyCode: 'AMD', currencySymbol: '֏' },
    { name: 'Aruba', phoneCode: '+297', tax: '3', currencyCode: 'AWG', currencySymbol: 'ƒ' },
    { name: 'Australia', phoneCode: '+61', tax: '10', currencyCode: 'AUD', currencySymbol: '$' },
    { name: 'Austria', phoneCode: '+43', tax: '20', currencyCode: 'EUR', currencySymbol: '€' },
    { name: 'Azerbaijan', phoneCode: '+994', tax: '18', currencyCode: 'AZN', currencySymbol: '₼' },
    { name: 'Bahamas', phoneCode: '+1-242', tax: '12', currencyCode: 'BSD', currencySymbol: '$' },
    { name: 'Bahrain', phoneCode: '+973', tax: '10', currencyCode: 'BHD', currencySymbol: 'BD' },
    { name: 'Bangladesh', phoneCode: '+880', tax: '15', currencyCode: 'BDT', currencySymbol: '৳' },
    { name: 'Barbados', phoneCode: '+1-246', tax: '17.5', currencyCode: 'BBD', currencySymbol: '$' },
    { name: 'Belarus', phoneCode: '+375', tax: '20', currencyCode: 'BYN', currencySymbol: 'Br' },
    { name: 'Belgium', phoneCode: '+32', tax: '21', currencyCode: 'EUR', currencySymbol: '€' },
    { name: 'Belize', phoneCode: '+501', tax: '12.5', currencyCode: 'BZD', currencySymbol: 'BZ$' },
    { name: 'Benin', phoneCode: '+229', tax: '18', currencyCode: 'XOF', currencySymbol: 'CFA' },
    { name: 'Bhutan', phoneCode: '+975', tax: '50', currencyCode: 'BTN', currencySymbol: 'Nu.' },
    { name: 'Bolivia', phoneCode: '+591', tax: '13', currencyCode: 'BOB', currencySymbol: 'Bs.' },
    { name: 'Bosnia and Herzegovina', phoneCode: '+387', tax: '17', currencyCode: 'BAM', currencySymbol: 'KM' },
    { name: 'Botswana', phoneCode: '+267', tax: '14', currencyCode: 'BWP', currencySymbol: 'P' },
    { name: 'Brazil', phoneCode: '+55', tax: '17', currencyCode: 'BRL', currencySymbol: 'R$' },
    { name: 'Bulgaria', phoneCode: '+359', tax: '20', currencyCode: 'BGN', currencySymbol: 'лв' },
    { name: 'Burkina Faso', phoneCode: '+226', tax: '18', currencyCode: 'XOF', currencySymbol: 'CFA' },
    { name: 'Burundi', phoneCode: '+257', tax: '18', currencyCode: 'BIF', currencySymbol: 'FBu' },
    { name: 'Cambodia', phoneCode: '+855', tax: '10', currencyCode: 'KHR', currencySymbol: '៛' },
    { name: 'Cameroon', phoneCode: '+237', tax: '19.25', currencyCode: 'XAF', currencySymbol: 'FCFA' },
    { name: 'Canada', phoneCode: '+1', tax: '5', currencyCode: 'CAD', currencySymbol: '$' },
    { name: 'Cape Verde', phoneCode: '+238', tax: '15', currencyCode: 'CVE', currencySymbol: '$' },
    { name: 'Central African Republic', phoneCode: '+236', tax: '19', currencyCode: 'XAF', currencySymbol: 'FCFA' },
    { name: 'Chad', phoneCode: '+235', tax: '18', currencyCode: 'XAF', currencySymbol: 'FCFA' },
    { name: 'Chile', phoneCode: '+56', tax: '19', currencyCode: 'CLP', currencySymbol: '$' },
    { name: 'China', phoneCode: '+86', tax: '13', currencyCode: 'CNY', currencySymbol: '¥' },
    { name: 'Colombia', phoneCode: '+57', tax: '19', currencyCode: 'COP', currencySymbol: '$' },
    { name: 'Comoros', phoneCode: '+269', tax: '10', currencyCode: 'KMF', currencySymbol: 'CF' },
    { name: 'Congo', phoneCode: '+242', tax: '16', currencyCode: 'XAF', currencySymbol: 'FCFA' },
    { name: 'Costa Rica', phoneCode: '+506', tax: '13', currencyCode: 'CRC', currencySymbol: '₡' },
    { name: 'Croatia', phoneCode: '+385', tax: '25', currencyCode: 'HRK', currencySymbol: 'kn' },
    { name: 'Cuba', phoneCode: '+53', tax: '20', currencyCode: 'CUP', currencySymbol: '$' },
    { name: 'Cyprus', phoneCode: '+357', tax: '19', currencyCode: 'EUR', currencySymbol: '€' },
    { name: 'Czech Republic', phoneCode: '+420', tax: '21', currencyCode: 'CZK', currencySymbol: 'Kč' },
    { name: 'Denmark', phoneCode: '+45', tax: '25', currencyCode: 'DKK', currencySymbol: 'kr' },
    { name: 'Djibouti', phoneCode: '+253', tax: '10', currencyCode: 'DJF', currencySymbol: 'Fdj' },
    { name: 'Dominica', phoneCode: '+1-767', tax: '15', currencyCode: 'XCD', currencySymbol: '$' },
    { name: 'Dominican Republic', phoneCode: '+1-809, +1-829, +1-849', tax: '18', currencyCode: 'DOP', currencySymbol: '$' },
    { name: 'Ecuador', phoneCode: '+593', tax: '12', currencyCode: 'USD', currencySymbol: '$' },
    { name: 'Egypt', phoneCode: '+20', tax: '14', currencyCode: 'EGP', currencySymbol: 'E£' },
    { name: 'El Salvador', phoneCode: '+503', tax: '13', currencyCode: 'USD', currencySymbol: '$' },
    { name: 'Equatorial Guinea', phoneCode: '+240', tax: '15', currencyCode: 'XAF', currencySymbol: 'FCFA' },
    { name: 'Eritrea', phoneCode: '+291', tax: '5', currencyCode: 'ERN', currencySymbol: 'Nfk' },
    { name: 'Estonia', phoneCode: '+372', tax: '22', currencyCode: 'EUR', currencySymbol: '€' },
    { name: 'Ethiopia', phoneCode: '+251', tax: '15', currencyCode: 'ETB', currencySymbol: 'Br' },
    { name: 'Euro Area', phoneCode: '', tax: '20.8', currencyCode: 'EUR', currencySymbol: '€' },
    { name: 'European Union', phoneCode: '', tax: '21.5', currencyCode: 'EUR', currencySymbol: '€' },
    { name: 'Fiji', phoneCode: '+679', tax: '9', currencyCode: 'FJD', currencySymbol: '$' },
    { name: 'Finland', phoneCode: '+358', tax: '24', currencyCode: 'EUR', currencySymbol: '€' },
    { name: 'France', phoneCode: '+33', tax: '20', currencyCode: 'EUR', currencySymbol: '€' },
    { name: 'Gabon', phoneCode: '+241', tax: '18', currencyCode: 'XAF', currencySymbol: 'FCFA' },
    { name: 'Gambia', phoneCode: '+220', tax: '15', currencyCode: 'GMD', currencySymbol: 'D' },
    { name: 'Georgia', phoneCode: '+995', tax: '18', currencyCode: 'GEL', currencySymbol: 'ლ' },
    { name: 'Germany', phoneCode: '+49', tax: '19', currencyCode: 'EUR', currencySymbol: '€' },
    { name: 'Ghana', phoneCode: '+233', tax: '15', currencyCode: 'GHS', currencySymbol: 'GH₵' },
    { name: 'Greece', phoneCode: '+30', tax: '24', currencyCode: 'EUR', currencySymbol: '€' },
    { name: 'Grenada', phoneCode: '+1-473', tax: '15', currencyCode: 'XCD', currencySymbol: '$' },
    { name: 'Guam', phoneCode: '+1-671', tax: '2', currencyCode: 'USD', currencySymbol: '$' },
    { name: 'Guatemala', phoneCode: '+502', tax: '12', currencyCode: 'GTQ', currencySymbol: 'Q' },
    { name: 'Guinea', phoneCode: '+224', tax: '18', currencyCode: 'GNF', currencySymbol: 'FG' },
    { name: 'Guyana', phoneCode: '+592', tax: '14', currencyCode: 'GYD', currencySymbol: '$' },
    { name: 'Haiti', phoneCode: '+509', tax: '10', currencyCode: 'HTG', currencySymbol: 'G' },
    { name: 'Honduras', phoneCode: '+504', tax: '15', currencyCode: 'HNL', currencySymbol: 'L' },
    { name: 'Hungary', phoneCode: '+36', tax: '27', currencyCode: 'HUF', currencySymbol: 'Ft' },
    { name: 'Iceland', phoneCode: '+354', tax: '24', currencyCode: 'ISK', currencySymbol: 'kr' },
    { name: 'India', phoneCode: '+91', tax: '18', currencyCode: 'INR', currencySymbol: '₹' },
    { name: 'Indonesia', phoneCode: '+62', tax: '11', currencyCode: 'IDR', currencySymbol: 'Rp' },
    { name: 'Ireland', phoneCode: '+353', tax: '23', currencyCode: 'EUR', currencySymbol: '€' },
    { name: 'Isle Of Man', phoneCode: '+44-1624', tax: '20', currencyCode: 'GBP', currencySymbol: '£' },
    { name: 'Israel', phoneCode: '+972', tax: '17', currencyCode: 'ILS', currencySymbol: '₪' },
    { name: 'Italy', phoneCode: '+39', tax: '22', currencyCode: 'EUR', currencySymbol: '€' },
    { name: 'Ivory Coast', phoneCode: '+225', tax: '18', currencyCode: 'XOF', currencySymbol: 'CFA' },
    { name: 'Jamaica', phoneCode: '+1-876', tax: '15', currencyCode: 'JMD', currencySymbol: '$' },
    { name: 'Japan', phoneCode: '+81', tax: '10', currencyCode: 'JPY', currencySymbol: '¥' },
    { name: 'Jordan', phoneCode: '+962', tax: '16', currencyCode: 'JOD', currencySymbol: 'د.ا' },
    { name: 'Kazakhstan', phoneCode: '+7', tax: '12', currencyCode: 'KZT', currencySymbol: '₸' },
    { name: 'Kenya', phoneCode: '+254', tax: '16', currencyCode: 'KES', currencySymbol: 'KSh' },
    { name: 'Kosovo', phoneCode: '+383', tax: '18', currencyCode: 'EUR', currencySymbol: '€' },
    { name: 'Kyrgyzstan', phoneCode: '+996', tax: '12', currencyCode: 'KGS', currencySymbol: 'сом' },
    { name: 'Laos', phoneCode: '+856', tax: '10', currencyCode: 'LAK', currencySymbol: '₭' },
    { name: 'Latvia', phoneCode: '+371', tax: '21', currencyCode: 'EUR', currencySymbol: '€' },
    { name: 'Lebanon', phoneCode: '+961', tax: '11', currencyCode: 'LBP', currencySymbol: 'ل.ل' },
    { name: 'Lesotho', phoneCode: '+266', tax: '15', currencyCode: 'LSL', currencySymbol: 'L' },
    { name: 'Liechtenstein', phoneCode: '+423', tax: '8.1', currencyCode: 'CHF', currencySymbol: 'CHF' },
    { name: 'Lithuania', phoneCode: '+370', tax: '21', currencyCode: 'EUR', currencySymbol: '€' },
    { name: 'Luxembourg', phoneCode: '+352', tax: '16', currencyCode: 'EUR', currencySymbol: '€' },
    { name: 'Macedonia', phoneCode: '+389', tax: '18', currencyCode: 'MKD', currencySymbol: 'ден' },
    { name: 'Madagascar', phoneCode: '+261', tax: '20', currencyCode: 'MGA', currencySymbol: 'Ar' },
    { name: 'Malawi', phoneCode: '+265', tax: '16.5', currencyCode: 'MWK', currencySymbol: 'MK' },
    { name: 'Malaysia', phoneCode: '+60', tax: '10', currencyCode: 'MYR', currencySymbol: 'RM' },
    { name: 'Mali', phoneCode: '+223', tax: '18', currencyCode: 'XOF', currencySymbol: 'CFA' },
    { name: 'Malta', phoneCode: '+356', tax: '18', currencyCode: 'EUR', currencySymbol: '€' },
    { name: 'Mauritania', phoneCode: '+222', tax: '16', currencyCode: 'MRU', currencySymbol: 'UM' },
    { name: 'Mauritius', phoneCode: '+230', tax: '15', currencyCode: 'MUR', currencySymbol: 'Rs' },
    { name: 'Mexico', phoneCode: '+52', tax: '16', currencyCode: 'MXN', currencySymbol: '$' },
    { name: 'Micronesia', phoneCode: '+691', tax: '5', currencyCode: 'USD', currencySymbol: '$' },
    { name: 'Moldova', phoneCode: '+373', tax: '20', currencyCode: 'MDL', currencySymbol: 'L' },
    { name: 'Monaco', phoneCode: '+377', tax: '20', currencyCode: 'EUR', currencySymbol: '€' },
    { name: 'Mongolia', phoneCode: '+976', tax: '10', currencyCode: 'MNT', currencySymbol: '₮' },
    { name: 'Montenegro', phoneCode: '+382', tax: '21', currencyCode: 'EUR', currencySymbol: '€' },
    { name: 'Morocco', phoneCode: '+212', tax: '20', currencyCode: 'MAD', currencySymbol: 'د.م.' },
    { name: 'Mozambique', phoneCode: '+258', tax: '16', currencyCode: 'MZN', currencySymbol: 'MT' },
    { name: 'Namibia', phoneCode: '+264', tax: '15', currencyCode: 'NAD', currencySymbol: 'N$' },
    { name: 'Nepal', phoneCode: '+977', tax: '13', currencyCode: 'NPR', currencySymbol: 'रू' },
    { name: 'Netherlands', phoneCode: '+31', tax: '21', currencyCode: 'EUR', currencySymbol: '€' },
    { name: 'New Zealand', phoneCode: '+64', tax: '15', currencyCode: 'NZD', currencySymbol: '$' },
    { name: 'Nicaragua', phoneCode: '+505', tax: '15', currencyCode: 'NIO', currencySymbol: 'C$' },
    { name: 'Niger', phoneCode: '+227', tax: '19', currencyCode: 'XOF', currencySymbol: 'CFA' },
    { name: 'Nigeria', phoneCode: '+234', tax: '7.5', currencyCode: 'NGN', currencySymbol: '₦' },
    { name: 'Norway', phoneCode: '+47', tax: '25', currencyCode: 'NOK', currencySymbol: 'kr' },
    { name: 'Oman', phoneCode: '+968', tax: '5', currencyCode: 'OMR', currencySymbol: 'ر.ع.' },
    { name: 'Pakistan', phoneCode: '+92', tax: '17', currencyCode: 'PKR', currencySymbol: '₨' },
    { name: 'Panama', phoneCode: '+507', tax: '7', currencyCode: 'PAB', currencySymbol: 'B/.' },
    { name: 'Papua New Guinea', phoneCode: '+675', tax: '10', currencyCode: 'PGK', currencySymbol: 'K' },
    { name: 'Paraguay', phoneCode: '+595', tax: '10', currencyCode: 'PYG', currencySymbol: '₲' },
    { name: 'Peru', phoneCode: '+51', tax: '18', currencyCode: 'PEN', currencySymbol: 'S/.' },
    { name: 'Philippines', phoneCode: '+63', tax: '12', currencyCode: 'PHP', currencySymbol: '₱' },
    { name: 'Poland', phoneCode: '+48', tax: '23', currencyCode: 'PLN', currencySymbol: 'zł' },
    { name: 'Portugal', phoneCode: '+351', tax: '23', currencyCode: 'EUR', currencySymbol: '€' },
    { name: 'Republic of the Congo', phoneCode: '+242', tax: '18.9', currencyCode: 'XAF', currencySymbol: 'FCFA' },
    { name: 'Romania', phoneCode: '+40', tax: '19', currencyCode: 'RON', currencySymbol: 'lei' },
    { name: 'Russia', phoneCode: '+7', tax: '20', currencyCode: 'RUB', currencySymbol: '₽' },
    { name: 'Rwanda', phoneCode: '+250', tax: '18', currencyCode: 'RWF', currencySymbol: 'RFw' },
    { name: 'Samoa', phoneCode: '+685', tax: '15', currencyCode: 'WST', currencySymbol: 'WS$' },
    { name: 'Saudi Arabia', phoneCode: '+966', tax: '15', currencyCode: 'SAR', currencySymbol: 'ر.س' },
    { name: 'Senegal', phoneCode: '+221', tax: '18', currencyCode: 'XOF', currencySymbol: 'CFA' },
    { name: 'Serbia', phoneCode: '+381', tax: '20', currencyCode: 'RSD', currencySymbol: 'din.' },
    { name: 'Seychelles', phoneCode: '+248', tax: '15', currencyCode: 'SCR', currencySymbol: 'SR' },
    { name: 'Sierra Leone', phoneCode: '+232', tax: '15', currencyCode: 'SLL', currencySymbol: 'Le' },
    { name: 'Singapore', phoneCode: '+65', tax: '7', currencyCode: 'SGD', currencySymbol: 'S$' },
    { name: 'Slovakia', phoneCode: '+421', tax: '20', currencyCode: 'EUR', currencySymbol: '€' },
    { name: 'Slovenia', phoneCode: '+386', tax: '22', currencyCode: 'EUR', currencySymbol: '€' },
    { name: 'Solomon Islands', phoneCode: '+677', tax: '10', currencyCode: 'SBD', currencySymbol: 'SI$' },
    { name: 'Somalia', phoneCode: '+252', tax: '10', currencyCode: 'SOS', currencySymbol: 'S' },
    { name: 'South Africa', phoneCode: '+27', tax: '15', currencyCode: 'ZAR', currencySymbol: 'R' },
    { name: 'South Korea', phoneCode: '+82', tax: '10', currencyCode: 'KRW', currencySymbol: '₩' },
    { name: 'Spain', phoneCode: '+34', tax: '21', currencyCode: 'EUR', currencySymbol: '€' },
    { name: 'Sri Lanka', phoneCode: '+94', tax: '18', currencyCode: 'LKR', currencySymbol: 'රු' },
    { name: 'St Lucia', phoneCode: '+1-758', tax: '15', currencyCode: 'XCD', currencySymbol: '$' },
    { name: 'Suriname', phoneCode: '+597', tax: '10', currencyCode: 'SRD', currencySymbol: '$' },
    { name: 'Swaziland', phoneCode: '+268', tax: '15', currencyCode: 'SZL', currencySymbol: 'E' },
    { name: 'Sweden', phoneCode: '+46', tax: '25', currencyCode: 'SEK', currencySymbol: 'kr' },
    { name: 'Switzerland', phoneCode: '+41', tax: '8.1', currencyCode: 'CHF', currencySymbol: 'CHF' },
    { name: 'Taiwan', phoneCode: '+886', tax: '5', currencyCode: 'TWD', currencySymbol: 'NT$' },
    { name: 'Tajikistan', phoneCode: '+992', tax: '15', currencyCode: 'TJS', currencySymbol: 'ЅМ' },
    { name: 'Tanzania', phoneCode: '+255', tax: '18', currencyCode: 'TZS', currencySymbol: 'TSh' },
    { name: 'Thailand', phoneCode: '+66', tax: '7', currencyCode: 'THB', currencySymbol: '฿' },
    { name: 'Togo', phoneCode: '+228', tax: '18', currencyCode: 'XOF', currencySymbol: 'CFA' },
    { name: 'Tonga', phoneCode: '+676', tax: '15', currencyCode: 'TOP', currencySymbol: 'T$' },
    { name: 'Trinidad And Tobago', phoneCode: '+1-868', tax: '12.5', currencyCode: 'TTD', currencySymbol: 'TT$' },
    { name: 'Tunisia', phoneCode: '+216', tax: '19', currencyCode: 'TND', currencySymbol: 'د.ت' },
    { name: 'Turkey', phoneCode: '+90', tax: '20', currencyCode: 'TRY', currencySymbol: '₺' },
    { name: 'Turkmenistan', phoneCode: '+993', tax: '15', currencyCode: 'TMT', currencySymbol: 'T' },
    { name: 'Uganda', phoneCode: '+256', tax: '18', currencyCode: 'UGX', currencySymbol: 'USh' },
    { name: 'Ukraine', phoneCode: '+380', tax: '20', currencyCode: 'UAH', currencySymbol: '₴' },
    { name: 'United Arab Emirates', phoneCode: '+971', tax: '5', currencyCode: 'AED', currencySymbol: 'د.إ' },
    { name: 'United Kingdom', phoneCode: '+44', tax: '20', currencyCode: 'GBP', currencySymbol: '£' },
    { name: 'United States', phoneCode: '+1', tax: '0', currencyCode: 'USD', currencySymbol: '$' },
    { name: 'Uruguay', phoneCode: '+598', tax: '22', currencyCode: 'UYU', currencySymbol: '$U' },
    { name: 'Uzbekistan', phoneCode: '+998', tax: '15', currencyCode: 'UZS', currencySymbol: 'лв' },
    { name: 'Vanuatu', phoneCode: '+678', tax: '15', currencyCode: 'VUV', currencySymbol: 'VT' },
    { name: 'Venezuela', phoneCode: '+58', tax: '16', currencyCode: 'VES', currencySymbol: 'Bs.S.' },
    { name: 'Vietnam', phoneCode: '+84', tax: '10', currencyCode: 'VND', currencySymbol: '₫' },
    { name: 'Zambia', phoneCode: '+260', tax: '16', currencyCode: 'ZMW', currencySymbol: 'ZK' },
    { name: 'Zimbabwe', phoneCode: '+263', tax: '14.5', currencyCode: 'ZWL', currencySymbol: 'Z$' },
];